export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_NEW = 'FETCH_PRODUCTS_NEW';
export const FETCH_PRODUCTS_LAPTOP = 'FETCH_PRODUCTS_LAPTOP';
export const FETCH_PRODUCTS_OFFICE = 'FETCH_PRODUCTS_OFFICE';
export const FETCH_PRODUCTS_DISCOUNT = 'FETCH_PRODUCTS_DISCOUNT';
export const FETCH_PRODUCTS_BEST = 'FETCH_PRODUCTS_BEST';

export const FETCH_PRODUCTS_OHTER = 'FETCH_PRODUCTS_OHTER';


export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';

export const FETCH_KEYSEARCH = 'FETCH_KEYSEARCH';
export const FETCH_USER = 'FETCH_USER';
export const UPDATE_USER = 'UPDATE_USER';



export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_CATEGORIES_PRODUCT = 'FETCH_CATEGORIES_PRODUCT';

export const STATUS_CATEGORY = "STATUS_CATEGORY";

export const FETCH_CART = "FETCH_CART";
export const ADD_CART = "ADD_CART";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_CART = "REMOVE_CART";
export const CLEAR_CART = " CLEAR_CART";

export const FETCH_BILL = "FETCH_BILL";
export const ADD_BILL = "ADD_BILL";
export const UPDATE_BILL = "UPDATE_BILL";
export const REMOVE_BILL = "REMOVE_BILL";
export const CLEAR_BILL = " CLEAR_BILL";

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const TOKEN_REDUX = 'TOKEN_REDUX';
export const UPDATE_ME = 'UPDATE_ME';

export const FETCH_RATINGS = "FETCH_RATINGS";
export const ADD_RATING = "ADD_RATING";
export const UPDATE_RATING = "UPDATE_RATING";
export const REMOVE_RATING = "REMOVE_RATING";

export const FETCH_WISHLIST = "FETCH_WISHLIST";
export const ADD_WISHLIST = "ADD_WISHLIST";
export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const REMOVE_WISHLIST = "REMOVE_WISHLIST";

export const FETCH_PRODUCERS = "FETCH_PRODUCERS";
export const FETCH_PRODUDCTS_PRODUCER = "FETCH_PRODUDCTS_PRODUCER";

export const SHOWLOADING = "SHOWLOADING";
export const HIDDENLOADING = "HIDDENLOADING";

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FIND_ORDERS = 'FIND_ORDERS';
export const EDIT_ORDER = 'EDIT_ORDER';
export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';

export const FETCH_ADDRESS = 'FETCH_ADDRESS';
export const FIND_ADDRESS = 'FIND_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';